### ISSUE TITLE
jdbc-pagination mysql extremely slow

### ISSUE THREAD

**Issue by AZhyrenkov** [logstash-plugins/logstash-input-jdbc#307]
I have logstash runnig in docker:
`FROM docker.elastic.co/logstash/logstash-oss:6.2.2`
And docker-compose:
```
version: '3'

services:
 logstash:
    container_name: my_logstash
    build:
      context: .
    restart: always
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./data:/data
    ports:
      - "5009:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

```

There is a pipeline.yml file:
```
input {
# companies
  jdbc {
    jdbc_driver_library => "/data/mysql-connector-java.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://connection_string"
    jdbc_user => "user"
    jdbc_password => "password"
    statement_filepath  => "/data/query1.sql"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "50000"

  }
# users
  jdbc {
    jdbc_driver_library => "/data/mysql-connector-java.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://connection_string"
    jdbc_user => "user"
    jdbc_password => "password"
    statement_filepath  => "/data/query2.sql"
    last_run_metadata_path => "/data/.last_run"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "50000"

  }

# users
}

output {
    amazon_es {
        hosts => [ "es_instance address.eu-west-1.es.amazonaws.com" ]
        region => "eu-west-1"
        index => "indexname"
        document_type => "user"
        document_id => "%{md5}"
    }
}
```
Users-input is just a simple query like this:
```
SELECT
        u.md5_hash                      as md5
        ,u.id                                  as id_users
        ,u.email                            as id_user_emails
FROM raw_users u
WHERE u.updated_at > :sql_last_value
```
Table raw_users has an indexes by id and updated_at

What jdbc_pagination is doing is, basically transforming query in dozen of such ones:
```
SELECT * FROM (SELECT
	u.md5_hash			as md5
	,u.id				as id_users
	,u.email		        as id_user_emails
FROM raw_users u
WHERE u.updated_at > '1970-01-01 00:00:00'
) AS `t1` LIMIT 50000 OFFSET 500000 
```
